#define DEFAULT 0
#define MIPMAP_VISUALIZE_LINEAR 1
#define MIPMAP_VISUALIZE_NEAREST 2
#define FRAGMENT_DEPTH 3
#define PARTIAL_DERIVATIVES_FRAGMENT_DEPTH 4
#define ANISOTROPIC_FILTERING 5
#define OVERDRAW_VISUALIZE 6
#define OVERSHADING_VISUALIZE 7
#define MESHDENSITY_VISUALIZE 8

#define CURRENT_VERSION 0
